/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
declare namespace dat {
  interface AbilitiesList {
    abilityType: string | null;
    abilityTypeId: dat.AbilityTypeId | null;
    challenging: number | null;
    cycle: number | null;
    difficult: number | null;
    hasShades: boolean | null;
    id: dat.AbilityId | null;
    name: string | null;
    requiredTraitIds: dat.TraitId[] | null;
    routine: number | null;
  }
  interface Ability {
    abilityTypeId: dat.AbilityTypeId;
    challenging: number | null;
    cycle: number | null;
    difficult: number | null;
    hasShades: boolean;
    id: dat.AbilityId;
    name: string;
    routine: number | null;
  }
  interface AbilityRequiredTrait {
    abilityId: dat.AbilityId;
    traitId: dat.TraitId;
  }
  interface AbilityType {
    id: dat.AbilityTypeId;
    name: string;
  }
  interface ActionResolutionType {
    id: dat.ActionResolutionTypeId;
    name: string;
    nameLong: string;
  }
  interface AgePool {
    id: dat.AgePoolId;
    mentalPool: number;
    minAge: number;
    physicalPool: number;
    stockId: dat.StockId;
  }
  interface AltSpellAreaOfEffectFacet {
    actions: number;
    id: dat.AltSpellAreaOfEffectFacetId;
    name: string;
    obstacle: number;
    resource: number;
    subFacet: string | null;
  }
  interface AltSpellDurationFacet {
    actions: number;
    id: dat.AltSpellDurationFacetId;
    name: string;
    obstacle: number;
    resource: number;
    subFacet: string | null;
  }
  interface AltSpellFacetType {
    id: dat.AltSpellFacetTypeId;
    name: string;
  }
  interface AltSpellHigherElementFacet {
    actions: number;
    id: dat.AltSpellHigherElementFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface AltSpellLawFacet {
    actions: number;
    id: dat.AltSpellLawFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface AltSpellLowerElementFacet {
    actions: number;
    id: dat.AltSpellLowerElementFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface AltSpellOriginFacet {
    actions: number;
    id: dat.AltSpellOriginFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface AltSpellPrimeElementFacet {
    actions: number;
    id: dat.AltSpellPrimeElementFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface DistanceUnit {
    id: dat.DistanceUnitId;
    name: string;
  }
  interface DoWActionResolutionList {
    ability: string | null;
    abilityId: dat.AbilityId | null;
    actionId: dat.DuelOfWitsActionId | null;
    isAgainstSkill: boolean | null;
    obstacle: number | null;
    opposingAbility: string | null;
    opposingAbilityId: dat.AbilityId | null;
    opposingAction: string | null;
    opposingActionId: dat.DuelOfWitsActionId | null;
    opposingModifier: number | null;
    opposingSkill: string | null;
    opposingSkillId: dat.SkillId | null;
    resolutionType: string | null;
    resolutionTypeId: dat.ActionResolutionTypeId | null;
    skill: string | null;
    skillId: dat.SkillId | null;
  }
  interface DoWActionTestList {
    ability: string | null;
    abilityId: dat.AbilityId | null;
    actionId: dat.DuelOfWitsActionId | null;
    skill: string | null;
    skillId: dat.SkillId | null;
  }
  interface DuelOfWitsAction {
    effect: string | null;
    id: dat.DuelOfWitsActionId;
    name: string;
    speakingThePart: string | null;
    special: string | null;
  }
  interface DuelOfWitsActionResolution {
    abilityId: dat.AbilityId | null;
    actionId: dat.DuelOfWitsActionId;
    id: dat.DuelOfWitsActionResolutionId;
    isAgainstSkill: boolean | null;
    obstacle: number | null;
    opposingAbilityId: dat.AbilityId | null;
    opposingActionId: dat.DuelOfWitsActionId;
    opposingModifier: number | null;
    opposingSkillId: dat.SkillId | null;
    resolutionTypeId: dat.ActionResolutionTypeId;
    skillId: dat.SkillId | null;
  }
  interface DuelOfWitsActionTest {
    abilityId: dat.AbilityId | null;
    actionId: dat.DuelOfWitsActionId;
    id: dat.DuelOfWitsActionTestId;
    skillId: dat.SkillId | null;
  }
  interface FightAction {
    actionCost: number | null;
    countsAsNoAction: boolean;
    effect: string | null;
    groupId: dat.FightActionGroupId;
    id: dat.FightActionId;
    name: string;
    restrictions: string | null;
    special: string | null;
    testExtra: string | null;
  }
  interface FightActionGroup {
    id: dat.FightActionGroupId;
    name: string;
  }
  interface FightActionResolution {
    abilityId: dat.AbilityId | null;
    actionId: dat.FightActionId;
    id: dat.FightActionResolutionId;
    isAgainstSkill: boolean | null;
    obstacle: number | null;
    opposingAbilityId: dat.AbilityId | null;
    opposingActionId: dat.FightActionId;
    opposingModifier: number | null;
    opposingSkillId: dat.SkillId | null;
    resolutionTypeId: dat.ActionResolutionTypeId;
    skillId: dat.SkillId | null;
  }
  interface FightActionResolutionList {
    ability: string | null;
    abilityId: dat.AbilityId | null;
    actionId: dat.FightActionId | null;
    isAgainstSkill: boolean | null;
    obstacle: number | null;
    opposingAbility: string | null;
    opposingAbilityId: dat.AbilityId | null;
    opposingAction: string | null;
    opposingActionId: dat.FightActionId | null;
    opposingModifier: number | null;
    opposingSkill: string | null;
    opposingSkillId: dat.SkillId | null;
    resolutionType: string | null;
    resolutionTypeId: dat.ActionResolutionTypeId | null;
    skill: string | null;
    skillId: dat.SkillId | null;
  }
  interface FightActionsList {
    actionCost: number | null;
    countsAsNoAction: boolean | null;
    effect: string | null;
    group: string | null;
    groupId: dat.FightActionGroupId | null;
    id: dat.FightActionId | null;
    name: string | null;
    restrictions: string | null;
    special: string | null;
    testExtra: string | null;
  }
  interface FightActionTest {
    abilityId: dat.AbilityId | null;
    actionId: dat.FightActionId;
    id: dat.FightActionTestId;
    skillId: dat.SkillId | null;
  }
  interface FightActionTestList {
    ability: string | null;
    abilityId: dat.AbilityId | null;
    actionId: dat.FightActionId | null;
    skill: string | null;
    skillId: dat.SkillId | null;
  }
  interface Lifepath {
    born: boolean;
    eitherPool: number;
    generalSkillPool: number;
    halfGspFromPrev: boolean;
    halfLspFromPrev: boolean;
    halfRpFromPrev: boolean;
    id: dat.LifepathId;
    isGspMultiplier: boolean;
    isLspMultiplier: boolean;
    isRpMultiplier: boolean;
    lifepathSkillPool: number;
    mentalPool: number;
    name: string;
    physicalPool: number;
    requirementText: string | null;
    resourcePoints: number;
    settingId: dat.SettingId;
    stockId: dat.StockId;
    traitPool: number;
    years: number[];
  }
  interface LifepathCompanion {
    companionName: string;
    givesSkills: boolean;
    gspMultiplier: number;
    lifepathId: dat.LifepathId;
    lspMultiplier: number;
    rpMultiplier: number;
  }
  interface LifepathCompanionSetting {
    companionSettingId: dat.SettingId;
    lifepathId: dat.LifepathId;
  }
  interface LifepathLead {
    lifepathId: dat.LifepathId;
    settingId: dat.SettingId;
  }
  interface LifepathRequirement {
    fulfillmentAmount: number;
    id: dat.LifepathRequirementId;
    lifepathId: dat.LifepathId;
    logicTypeId: dat.LogicTypeId;
    mustFulfill: boolean;
  }
  interface LifepathRequirementBlock {
    fulfillmentAmount: number | null;
    id: dat.LifepathRequirementBlockId | null;
    lifepathId: dat.LifepathId | null;
    logicType: string | null;
    logicTypeId: dat.LogicTypeId | null;
    mustFulfill: boolean | null;
  }
  interface LifepathRequirementBlockItem {
    attribute: string | null;
    attributeId: dat.AbilityId | null;
    forCompanion: boolean | null;
    lifepath: string | null;
    lifepathId: dat.LifepathId | null;
    max: number | null;
    min: number | null;
    requirementId: dat.LifepathRequirementBlockId | null;
    requirementType: string | null;
    requirementTypeId: dat.RequirementItemTypeId | null;
    setting: string | null;
    settingId: dat.SettingId | null;
    skill: string | null;
    skillId: dat.SkillId | null;
    trait: string | null;
    traitId: dat.TraitId | null;
  }
  interface LifepathRequirementItem {
    attributeId: dat.AbilityId | null;
    forCompanion: boolean;
    id: dat.LifepathRequirementItemId;
    lifepathId: dat.LifepathId | null;
    max: number | null;
    min: number | null;
    requirementId: dat.LifepathRequirementId;
    requirementTypeId: dat.RequirementItemTypeId;
    settingId: dat.SettingId | null;
    skillId: dat.SkillId | null;
    traitId: dat.TraitId | null;
  }
  interface LifepathSkill {
    index: number;
    lifepathId: dat.LifepathId;
    skillId: dat.SkillId;
  }
  interface LifepathsList {
    born: boolean | null;
    companionGivesSkills: boolean | null;
    companionGspMultiplier: number | null;
    companionLspMultiplier: number | null;
    companionName: string | null;
    companionRpMultiplier: number | null;
    companionSettingIds: dat.SettingId[] | null;
    eitherPool: number | null;
    generalSkillPool: number | null;
    halfGspFromPrev: boolean | null;
    halfLspFromPrev: boolean | null;
    halfRpFromPrev: boolean | null;
    id: dat.LifepathId | null;
    isGspMultiplier: boolean | null;
    isLspMultiplier: boolean | null;
    isRpMultiplier: boolean | null;
    leadIds: dat.SettingId[] | null;
    lifepathSkillPool: number | null;
    mentalPool: number | null;
    name: string | null;
    physicalPool: number | null;
    requirementText: string | null;
    resourcePoints: number | null;
    rulesets: string[] | null;
    setting: string | null;
    settingId: dat.SettingId | null;
    skillIds: dat.SkillId[] | null;
    stock: string | null;
    stockId: dat.StockId | null;
    traitIds: dat.TraitId[] | null;
    traitPool: number | null;
    years: number[] | null;
  }
  interface LifepathTrait {
    index: number;
    lifepathId: dat.LifepathId;
    traitId: dat.TraitId;
  }
  interface LogicType {
    id: dat.LogicTypeId;
    name: string;
  }
  interface PracticeList {
    ability: string | null;
    abilityId: dat.AbilityId | null;
    challenging: number | null;
    cycle: number | null;
    difficult: number | null;
    id: string | null;
    routine: number | null;
    skillType: string | null;
    skillTypeId: dat.SkillTypeId | null;
  }
  interface Question {
    attributeId1: dat.AbilityId | null;
    attributeId2: dat.AbilityId | null;
    id: dat.QuestionId;
    name: string;
    question: string;
  }
  interface QuestionList {
    attributeId1: dat.AbilityId | null;
    attributeId2: dat.AbilityId | null;
    attributeName1: string | null;
    attributeName2: string | null;
    id: dat.QuestionId | null;
    name: string | null;
    question: string | null;
  }
  interface RangeAndCoverAction {
    effect: string | null;
    groupId: dat.RangeAndCoverActionGroupId;
    however: string | null;
    id: dat.RangeAndCoverActionId;
    isOpenEnded: boolean;
    modifier: number;
    name: string;
    specialAction: string | null;
    specialRestriction: string | null;
    useFoRKs: boolean;
    usePositionAdvantage: boolean;
    useStrideAdvantage: boolean;
    useWeaponRangeAdvantage: boolean;
  }
  interface RangeAndCoverActionGroup {
    id: dat.RangeAndCoverActionGroupId;
    name: string;
  }
  interface RangeAndCoverActionResolution {
    abilityId: dat.AbilityId | null;
    actionId: dat.RangeAndCoverActionId;
    id: dat.RangeAndCoverActionResolutionId;
    isAgainstSkill: boolean | null;
    obstacle: number | null;
    opposingAbilityId: dat.AbilityId | null;
    opposingActionId: dat.RangeAndCoverActionId;
    opposingModifier: number | null;
    opposingSkillId: dat.SkillId | null;
    resolutionTypeId: dat.ActionResolutionTypeId;
    skillId: dat.SkillId | null;
  }
  interface RangeAndCoverActionResolutionList {
    ability: string | null;
    abilityId: dat.AbilityId | null;
    actionId: dat.RangeAndCoverActionId | null;
    isAgainstSkill: boolean | null;
    obstacle: number | null;
    opposingAbility: string | null;
    opposingAbilityId: dat.AbilityId | null;
    opposingAction: string | null;
    opposingActionId: dat.RangeAndCoverActionId | null;
    opposingModifier: number | null;
    opposingSkill: string | null;
    opposingSkillId: dat.SkillId | null;
    resolutionType: string | null;
    resolutionTypeId: dat.ActionResolutionTypeId | null;
    skill: string | null;
    skillId: dat.SkillId | null;
  }
  interface RangeAndCoverActionsList {
    effect: string | null;
    group: string | null;
    groupId: dat.RangeAndCoverActionGroupId | null;
    however: string | null;
    id: dat.RangeAndCoverActionId | null;
    isOpenEnded: boolean | null;
    name: string | null;
    specialAction: string | null;
    specialRestriction: string | null;
    useFoRKs: boolean | null;
    usePositionAdvantage: boolean | null;
    useStrideAdvantage: boolean | null;
    useWeaponRangeAdvantage: boolean | null;
  }
  interface RequirementItemType {
    id: dat.RequirementItemTypeId;
    name: string;
  }
  interface Resource {
    description: string | null;
    id: dat.ResourceId;
    name: string;
    resourceTypeId: dat.ResourceTypeId;
    stockId: dat.StockId;
    variableCost: boolean;
  }
  interface ResourceCost {
    cost: number;
    description: string | null;
    id: dat.ResourceCostId;
    resourceId: dat.ResourceId;
  }
  interface ResourceMagicDetail {
    actions: number;
    actionsMultiply: boolean;
    areaOfEffectId: dat.SpellAreaOfEffectFacetId;
    areaOfEffectModifierId: dat.UnitModifierId | null;
    areaOfEffectUnitId: dat.DistanceUnitId | null;
    durationId: dat.SpellDurationFacetId;
    durationUnitId: dat.TimeUnitId | null;
    element1Id: dat.SpellElementFacetId;
    element2Id: dat.SpellElementFacetId | null;
    element3Id: dat.SpellElementFacetId | null;
    id: dat.ResourceMagicDetailId;
    impetus1Id: dat.SpellImpetusFacetId;
    impetus2Id: dat.SpellImpetusFacetId | null;
    originId: dat.SpellOriginFacetId;
    originModifierId: dat.UnitModifierId | null;
    resourceId: dat.ResourceId;
  }
  interface ResourceMagicDetailsList {
    actions: number | null;
    actionsMultiply: boolean | null;
    areaOfEffect: string | null;
    areaOfEffectId: dat.SpellAreaOfEffectFacetId | null;
    areaOfEffectModifier: string | null;
    areaOfEffectModifierId: dat.UnitModifierId | null;
    areaOfEffectUnit: string | null;
    areaOfEffectUnitId: dat.DistanceUnitId | null;
    duration: string | null;
    durationId: dat.SpellDurationFacetId | null;
    element1: string | null;
    element1Id: dat.SpellElementFacetId | null;
    element2: string | null;
    element2Id: dat.SpellElementFacetId | null;
    element3: string | null;
    element3Id: dat.SpellElementFacetId | null;
    id: dat.ResourceMagicDetailId | null;
    impetus1: string | null;
    impetus1Id: dat.SpellImpetusFacetId | null;
    impetus2: string | null;
    impetus2Id: dat.SpellImpetusFacetId | null;
    origin: string | null;
    originId: dat.SpellOriginFacetId | null;
    resourceId: dat.ResourceId | null;
  }
  interface ResourceMagicObstacle {
    description: string | null;
    id: dat.ResourceMagicObstacleId;
    obstacle: number | null;
    obstacleAbility1Id: dat.AbilityId | null;
    obstacleAbility2Id: dat.AbilityId | null;
    obstacleCaret: boolean;
    resourceId: dat.ResourceId;
  }
  interface ResourceMagicObstaclesList {
    description: string | null;
    id: dat.ResourceMagicObstacleId | null;
    obstacle: number | null;
    obstacleAbility1: string | null;
    obstacleAbility1Id: dat.AbilityId | null;
    obstacleAbility2: string | null;
    obstacleAbility2Id: dat.AbilityId | null;
    obstacleCaret: boolean | null;
    resourceId: dat.ResourceId | null;
  }
  interface ResourceModifier {
    cost: number;
    description: string | null;
    id: dat.ResourceModifierId;
    isPerCost: boolean;
    resourceId: dat.ResourceId;
  }
  interface ResourcesList {
    costDescriptions: string[] | null;
    costs: number[] | null;
    description: string | null;
    id: dat.ResourceId | null;
    modifierDescriptions: string[] | null;
    modifierIsPerCosts: boolean[] | null;
    modifiers: number[] | null;
    name: string | null;
    resourceType: string | null;
    resourceTypeId: dat.ResourceTypeId | null;
    rulesets: string[] | null;
    stock: string | null;
    stockId: dat.StockId | null;
    variableCost: boolean | null;
  }
  interface ResourceType {
    id: dat.ResourceTypeId;
    name: string;
  }
  interface Ruleset {
    id: dat.RulesetId;
    isExpansion: boolean;
    isOfficial: boolean;
    isPublic: boolean;
    name: string;
  }
  interface RulesetExpansion {
    expansionId: dat.RulesetId;
    rulesetId: dat.RulesetId;
  }
  interface RulesetLifepath {
    lifepathId: dat.LifepathId;
    rulesetId: dat.RulesetId;
  }
  interface RulesetResource {
    resourceId: dat.ResourceId;
    rulesetId: dat.RulesetId;
  }
  interface RulesetSetting {
    rulesetId: dat.RulesetId;
    settingId: dat.SettingId;
  }
  interface RulesetSkill {
    rulesetId: dat.RulesetId;
    skillId: dat.SkillId;
  }
  interface RulesetsList {
    expansionIds: dat.RulesetId[] | null;
    id: dat.RulesetId | null;
    isExpansion: boolean | null;
    isOfficial: boolean | null;
    isPublic: boolean | null;
    name: string | null;
  }
  interface RulesetStock {
    rulesetId: dat.RulesetId;
    stockId: dat.StockId;
  }
  interface RulesetTrait {
    rulesetId: dat.RulesetId;
    traitId: dat.TraitId;
  }
  interface Setting {
    id: dat.SettingId;
    isSubsetting: boolean;
    name: string;
    nameShort: string;
    stockId: dat.StockId;
  }
  interface SettingsList {
    id: dat.SettingId | null;
    isSubsetting: boolean | null;
    name: string | null;
    nameShort: string | null;
    rulesets: string[] | null;
    stockId: dat.StockId | null;
    stockName: string | null;
  }
  interface Skill {
    categoryId: dat.SkillCategoryId;
    description: string | null;
    dontList: boolean;
    id: dat.SkillId;
    isMagical: boolean;
    isTraining: boolean;
    name: string;
    restrictionAbilityId: dat.AbilityId | null;
    restrictionOnlyStockId: dat.StockId | null;
    restrictionWhenBurning: boolean | null;
    root1Id: dat.AbilityId | null;
    root2Id: dat.AbilityId | null;
    stockId: dat.StockId | null;
    toolDescription: string | null;
    toolTypeId: dat.SkillToolTypeId | null;
    typeId: dat.SkillTypeId;
  }
  interface SkillCategory {
    id: dat.SkillCategoryId;
    name: string;
  }
  interface SkillsList {
    category: string | null;
    categoryId: dat.SkillCategoryId | null;
    description: string | null;
    dontList: boolean | null;
    id: dat.SkillId | null;
    isMagical: boolean | null;
    isTraining: boolean | null;
    name: string | null;
    restrictionAbility: string | null;
    restrictionAbilityId: dat.AbilityId | null;
    restrictionOnlyStock: string | null;
    restrictionOnlyStockId: dat.StockId | null;
    restrictionWhenBurning: boolean | null;
    rootIds: dat.AbilityId[] | null;
    roots: string[] | null;
    rulesets: string[] | null;
    stock: string | null;
    stockId: dat.StockId | null;
    subskillIds: dat.SkillId[] | null;
    tool: string | null;
    toolDescription: string | null;
    toolTypeId: dat.SkillToolTypeId | null;
    type: string | null;
    typeId: dat.SkillTypeId | null;
  }
  interface SkillSubskill {
    skillId: dat.SkillId;
    subskillId: dat.SkillId;
  }
  interface SkillToolType {
    id: dat.SkillToolTypeId;
    name: string;
  }
  interface SkillType {
    challenging: number;
    cycle: number;
    difficult: number;
    id: dat.SkillTypeId;
    name: string;
    routine: number;
  }
  interface SpellAreaOfEffectFacet {
    actions: number;
    id: dat.SpellAreaOfEffectFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface SpellDurationFacet {
    actions: number;
    id: dat.SpellDurationFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface SpellElementFacet {
    actions: number;
    id: dat.SpellElementFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface SpellFacetType {
    id: dat.SpellFacetTypeId;
    name: string;
  }
  interface SpellImpetusFacet {
    actions: number;
    id: dat.SpellImpetusFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface SpellOriginFacet {
    actions: number;
    id: dat.SpellOriginFacetId;
    name: string;
    obstacle: number;
    resource: number;
  }
  interface Stock {
    id: dat.StockId;
    name: string;
    namePlural: string;
    stride: number;
  }
  interface StocksList {
    id: dat.StockId | null;
    name: string | null;
    namePlural: string | null;
    rulesets: string[] | null;
    settingIds: dat.SettingId[] | null;
    stride: number | null;
  }
  interface TimeUnit {
    id: dat.TimeUnitId;
    name: string;
  }
  interface Trait {
    categoryId: dat.TraitCategoryId;
    cost: number;
    description: string | null;
    id: dat.TraitId;
    name: string;
    stockId: dat.StockId | null;
    typeId: dat.TraitTypeId;
  }
  interface TraitCallOnAbility {
    abilityId: dat.AbilityId;
    traitId: dat.TraitId;
  }
  interface TraitCallOnSkill {
    skillId: dat.SkillId;
    traitId: dat.TraitId;
  }
  interface TraitCategory {
    id: dat.TraitCategoryId;
    name: string;
  }
  interface TraitGrantsResource {
    isChoice: boolean;
    minCost: number;
    resourceId: dat.ResourceId;
    traitId: dat.TraitId;
  }
  interface TraitsList {
    callOnAbilityIds: dat.AbilityId[] | null;
    callOnSkillIds: dat.SkillId[] | null;
    category: string | null;
    categoryId: dat.TraitCategoryId | null;
    cost: number | null;
    description: string | null;
    grantsResourceIds: dat.ResourceId[] | null;
    grantsResourceIsChoice: boolean | null;
    grantsResourceMinCosts: number[] | null;
    id: dat.TraitId | null;
    name: string | null;
    rulesets: string[] | null;
    stock: string | null;
    stockId: dat.StockId | null;
    type: string | null;
    typeId: dat.TraitTypeId | null;
  }
  interface TraitType {
    id: dat.TraitTypeId;
    name: string;
  }
  interface UnitModifier {
    id: dat.UnitModifierId;
    name: string;
  }
}
declare namespace meta {
  interface Migration {
    executedAt: Date | null;
    id: meta.MigrationId;
    name: string;
  }
}
