import fs from "fs";
import path from "path";

import { Client } from "@rmp135/sql-ts";

import { Env } from "../utils/env";


void (async () => {
  const initial = await Client
    .fromConfig({
      dialect: "postgres",
      client: "pg",
      connection: { user: Env.dbUser, password: Env.dbPass, host: Env.dbHost, port: Env.dbPort, database: Env.dbName },
      globalOptionality: "required",
      schemaAsNamespace: true,
      schemas: ["meta", "usr", "dat"],
      typeOverrides: {
        "dat.AbilitiesList.abilityTypeId": "dat.AbilityTypeId",
        "dat.AbilitiesList.id": "dat.AbilityId",
        "dat.AbilitiesList.requiredTraitId": "dat.TraitId",
        "dat.Ability.abilityTypeId": "dat.AbilityTypeId",
        "dat.Ability.id": "dat.AbilityId",
        "dat.Ability.requiredTraitId": "dat.TraitId",
        "dat.AbilityType.id": "dat.AbilityTypeId",
        "dat.ActionResolutionType.id": "dat.ActionResolutionTypeId",
        "dat.AgePool.id": "dat.AgePoolId",
        "dat.AgePool.stockId": "dat.StockId",
        "dat.AltSpellAreaOfEffectFacet.id": "dat.AltSpellAreaOfEffectFacetId",
        "dat.AltSpellDurationFacet.id": "dat.AltSpellDurationFacetId",
        "dat.AltSpellFacetType.id": "dat.AltSpellFacetTypeId",
        "dat.AltSpellHigherElementFacet.id": "dat.AltSpellHigherElementFacetId",
        "dat.AltSpellLawFacet.id": "dat.AltSpellLawFacetId",
        "dat.AltSpellLowerElementFacet.id": "dat.AltSpellLowerElementFacetId",
        "dat.AltSpellOriginFacet.id": "dat.AltSpellOriginFacetId",
        "dat.AltSpellPrimeElementFacet.id": "dat.AltSpellPrimeElementFacetId",
        "dat.DistanceUnit.id": "dat.DistanceUnitId",
        "dat.DoWActionResolutionList.abilityId": "dat.AbilityId",
        "dat.DoWActionResolutionList.actionId": "dat.DuelOfWitsActionId",
        "dat.DoWActionResolutionList.opposingAbilityId": "dat.AbilityId",
        "dat.DoWActionResolutionList.opposingActionId": "dat.DuelOfWitsActionId",
        "dat.DoWActionResolutionList.opposingSkillId": "dat.SkillId",
        "dat.DoWActionResolutionList.resolutionTypeId": "dat.ActionResolutionTypeId",
        "dat.DoWActionResolutionList.skillId": "dat.SkillId",
        "dat.DoWActionTestList.abilityId": "dat.AbilityId",
        "dat.DoWActionTestList.actionId": "dat.DuelOfWitsActionId",
        "dat.DoWActionTestList.skillId": "dat.SkillId",
        "dat.DuelOfWitsAction.id": "dat.DuelOfWitsActionId",
        "dat.DuelOfWitsActionResolution.abilityId": "dat.AbilityId",
        "dat.DuelOfWitsActionResolution.actionId": "dat.DuelOfWitsActionId",
        "dat.DuelOfWitsActionResolution.id": "dat.DuelOfWitsActionResolutionId",
        "dat.DuelOfWitsActionResolution.opposingAbilityId": "dat.AbilityId",
        "dat.DuelOfWitsActionResolution.opposingActionId": "dat.DuelOfWitsActionId",
        "dat.DuelOfWitsActionResolution.opposingSkillId": "dat.SkillId",
        "dat.DuelOfWitsActionResolution.resolutionTypeId": "dat.ActionResolutionTypeId",
        "dat.DuelOfWitsActionResolution.skillId": "dat.SkillId",
        "dat.DuelOfWitsActionTest.abilityId": "dat.AbilityId",
        "dat.DuelOfWitsActionTest.actionId": "dat.DuelOfWitsActionId",
        "dat.DuelOfWitsActionTest.id": "dat.DuelOfWitsActionTestId",
        "dat.DuelOfWitsActionTest.skillId": "dat.SkillId",
        "dat.FightAction.groupId": "dat.FightActionGroupId",
        "dat.FightAction.id": "dat.FightActionId",
        "dat.FightActionGroup.id": "dat.FightActionGroupId",
        "dat.FightActionResolution.abilityId": "dat.AbilityId",
        "dat.FightActionResolution.actionId": "dat.FightActionId",
        "dat.FightActionResolution.id": "dat.FightActionResolutionId",
        "dat.FightActionResolution.opposingAbilityId": "dat.AbilityId",
        "dat.FightActionResolution.opposingActionId": "dat.FightActionId",
        "dat.FightActionResolution.opposingSkillId": "dat.SkillId",
        "dat.FightActionResolution.resolutionTypeId": "dat.ActionResolutionTypeId",
        "dat.FightActionResolution.skillId": "dat.SkillId",
        "dat.FightActionResolutionList.abilityId": "dat.AbilityId",
        "dat.FightActionResolutionList.actionId": "dat.FightActionId",
        "dat.FightActionResolutionList.opposingAbilityId": "dat.AbilityId",
        "dat.FightActionResolutionList.opposingActionId": "dat.FightActionId",
        "dat.FightActionResolutionList.opposingSkillId": "dat.SkillId",
        "dat.FightActionResolutionList.resolutionTypeId": "dat.ActionResolutionTypeId",
        "dat.FightActionResolutionList.skillId": "dat.SkillId",
        "dat.FightActionTest.abilityId": "dat.AbilityId",
        "dat.FightActionTest.actionId": "dat.FightActionId",
        "dat.FightActionTest.id": "dat.FightActionTestId",
        "dat.FightActionTest.skillId": "dat.SkillId",
        "dat.FightActionTestList.abilityId": "dat.AbilityId",
        "dat.FightActionTestList.actionId": "dat.FightActionId",
        "dat.FightActionTestList.skillId": "dat.SkillId",
        "dat.FightActionsList.groupId": "dat.FightActionGroupId",
        "dat.FightActionsList.id": "dat.FightActionId",
        "dat.Lifepath.id": "dat.LifepathId",
        "dat.Lifepath.settingId": "dat.SettingId",
        "dat.Lifepath.stockId": "dat.StockId",
        "dat.Lifepath.years": "number[]",
        "dat.LifepathCompanion.lifepathId": "dat.LifepathId",
        "dat.LifepathCompanionSetting.companionSettingId": "dat.SettingId",
        "dat.LifepathCompanionSetting.lifepathId": "dat.LifepathId",
        "dat.LifepathLead.lifepathId": "dat.LifepathId",
        "dat.LifepathLead.settingId": "dat.SettingId",
        "dat.LifepathRequirement.id": "dat.LifepathRequirementId",
        "dat.LifepathRequirement.lifepathId": "dat.LifepathId",
        "dat.LifepathRequirement.logicTypeId": "dat.LogicTypeId",
        "dat.LifepathRequirementBlockItem.attributeId": "dat.AbilityId",
        "dat.LifepathRequirementBlockItem.lifepathId": "dat.LifepathId",
        "dat.LifepathRequirementBlockItem.requirementId": "dat.LifepathRequirementBlockId",
        "dat.LifepathRequirementBlockItem.requirementTypeId": "dat.RequirementItemTypeId",
        "dat.LifepathRequirementBlockItem.settingId": "dat.SettingId",
        "dat.LifepathRequirementBlockItem.skillId": "dat.SkillId",
        "dat.LifepathRequirementBlockItem.traitId": "dat.TraitId",
        "dat.LifepathRequirementBlock.id": "dat.LifepathRequirementBlockId",
        "dat.LifepathRequirementBlock.lifepathId": "dat.LifepathId",
        "dat.LifepathRequirementBlock.logicTypeId": "dat.LogicTypeId",
        "dat.LifepathRequirementItem.attributeId": "dat.AbilityId",
        "dat.LifepathRequirementItem.id": "dat.LifepathRequirementItemId",
        "dat.LifepathRequirementItem.lifepathId": "dat.LifepathId",
        "dat.LifepathRequirementItem.requirementId": "dat.LifepathRequirementId",
        "dat.LifepathRequirementItem.requirementTypeId": "dat.RequirementItemTypeId",
        "dat.LifepathRequirementItem.settingId": "dat.SettingId",
        "dat.LifepathRequirementItem.skillId": "dat.SkillId",
        "dat.LifepathRequirementItem.traitId": "dat.TraitId",
        "dat.LifepathSkill.lifepathId": "dat.LifepathId",
        "dat.LifepathSkill.skillId": "dat.SkillId",
        "dat.LifepathTrait.lifepathId": "dat.LifepathId",
        "dat.LifepathTrait.traitId": "dat.TraitId",
        "dat.LifepathsList.companionSettingIds": "dat.SettingId[]",
        "dat.LifepathsList.id": "dat.LifepathId",
        "dat.LifepathsList.leadIds": "dat.SettingId[]",
        "dat.LifepathsList.settingId": "dat.SettingId",
        "dat.LifepathsList.skillIds": "dat.SkillId[]",
        "dat.LifepathsList.stockId": "dat.StockId",
        "dat.LifepathsList.traitIds": "dat.TraitId[]",
        "dat.LifepathsList.years": "number[]",
        "dat.LogicType.id": "dat.LogicTypeId",
        "dat.PracticeList.abilityId": "dat.AbilityId",
        "dat.PracticeList.skillTypeId": "dat.SkillTypeId",
        "dat.Question.attributeId1": "dat.AbilityId",
        "dat.Question.attributeId2": "dat.AbilityId",
        "dat.Question.id": "dat.QuestionId",
        "dat.QuestionList.attributeId1": "dat.AbilityId",
        "dat.QuestionList.attributeId2": "dat.AbilityId",
        "dat.QuestionList.id": "dat.QuestionId",
        "dat.RangeAndCoverAction.groupId": "dat.RangeAndCoverActionGroupId",
        "dat.RangeAndCoverAction.id": "dat.RangeAndCoverActionId",
        "dat.RangeAndCoverActionGroup.id": "dat.RangeAndCoverActionGroupId",
        "dat.RangeAndCoverActionResolution.abilityId": "dat.AbilityId",
        "dat.RangeAndCoverActionResolution.actionId": "dat.RangeAndCoverActionId",
        "dat.RangeAndCoverActionResolution.id": "dat.RangeAndCoverActionResolutionId",
        "dat.RangeAndCoverActionResolution.opposingAbilityId": "dat.AbilityId",
        "dat.RangeAndCoverActionResolution.opposingActionId": "dat.RangeAndCoverActionId",
        "dat.RangeAndCoverActionResolution.opposingSkillId": "dat.SkillId",
        "dat.RangeAndCoverActionResolution.resolutionTypeId": "dat.ActionResolutionTypeId",
        "dat.RangeAndCoverActionResolution.skillId": "dat.SkillId",
        "dat.RangeAndCoverActionResolutionList.abilityId": "dat.AbilityId",
        "dat.RangeAndCoverActionResolutionList.actionId": "dat.RangeAndCoverActionId",
        "dat.RangeAndCoverActionResolutionList.opposingAbilityId": "dat.AbilityId",
        "dat.RangeAndCoverActionResolutionList.opposingActionId": "dat.RangeAndCoverActionId",
        "dat.RangeAndCoverActionResolutionList.opposingSkillId": "dat.SkillId",
        "dat.RangeAndCoverActionResolutionList.resolutionTypeId": "dat.ActionResolutionTypeId",
        "dat.RangeAndCoverActionResolutionList.skillId": "dat.SkillId",
        "dat.RangeAndCoverActionsList.groupId": "dat.RangeAndCoverActionGroupId",
        "dat.RangeAndCoverActionsList.id": "dat.RangeAndCoverActionId",
        "dat.RequirementItemType.id": "dat.RequirementItemTypeId",
        "dat.Resource.id": "dat.ResourceId",
        "dat.Resource.resourceTypeId": "dat.ResourceTypeId",
        "dat.Resource.stockId": "dat.StockId",
        "dat.ResourceCost.id": "dat.ResourceCostId",
        "dat.ResourceCost.resourceId": "dat.ResourceId",
        "dat.ResourceMagicDetail.areaOfEffectId": "dat.SpellAreaOfEffectFacetId",
        "dat.ResourceMagicDetail.areaOfEffectModifierId": "dat.UnitModifierId",
        "dat.ResourceMagicDetail.areaOfEffectUnitId": "dat.DistanceUnitId",
        "dat.ResourceMagicDetail.durationId": "dat.SpellDurationFacetId",
        "dat.ResourceMagicDetail.durationUnitId": "dat.TimeUnitId",
        "dat.ResourceMagicDetail.element1Id": "dat.SpellElementFacetId",
        "dat.ResourceMagicDetail.element2Id": "dat.SpellElementFacetId",
        "dat.ResourceMagicDetail.element3Id": "dat.SpellElementFacetId",
        "dat.ResourceMagicDetail.id": "dat.ResourceMagicDetailId",
        "dat.ResourceMagicDetail.impetus1Id": "dat.SpellImpetusFacetId",
        "dat.ResourceMagicDetail.impetus2Id": "dat.SpellImpetusFacetId",
        "dat.ResourceMagicDetail.originId": "dat.SpellOriginFacetId",
        "dat.ResourceMagicDetail.originModifierId": "dat.UnitModifierId",
        "dat.ResourceMagicDetail.resourceId": "dat.ResourceId",
        "dat.ResourceMagicDetailsList.areaOfEffectId": "dat.SpellAreaOfEffectFacetId",
        "dat.ResourceMagicDetailsList.areaOfEffectModifierId": "dat.UnitModifierId",
        "dat.ResourceMagicDetailsList.areaOfEffectUnitId": "dat.DistanceUnitId",
        "dat.ResourceMagicDetailsList.durationId": "dat.SpellDurationFacetId",
        "dat.ResourceMagicDetailsList.element1Id": "dat.SpellElementFacetId",
        "dat.ResourceMagicDetailsList.element2Id": "dat.SpellElementFacetId",
        "dat.ResourceMagicDetailsList.element3Id": "dat.SpellElementFacetId",
        "dat.ResourceMagicDetailsList.id": "dat.ResourceMagicDetailId",
        "dat.ResourceMagicDetailsList.impetus1Id": "dat.SpellImpetusFacetId",
        "dat.ResourceMagicDetailsList.impetus2Id": "dat.SpellImpetusFacetId",
        "dat.ResourceMagicDetailsList.originId": "dat.SpellOriginFacetId",
        "dat.ResourceMagicDetailsList.resourceId": "dat.ResourceId",
        "dat.ResourceMagicObstacle.id": "dat.ResourceMagicObstacleId",
        "dat.ResourceMagicObstacle.obstacleAbility1Id": "dat.AbilityId",
        "dat.ResourceMagicObstacle.obstacleAbility2Id": "dat.AbilityId",
        "dat.ResourceMagicObstacle.resourceId": "dat.ResourceId",
        "dat.ResourceMagicObstaclesList.id": "dat.ResourceMagicObstacleId",
        "dat.ResourceMagicObstaclesList.obstacleAbility1Id": "dat.AbilityId",
        "dat.ResourceMagicObstaclesList.obstacleAbility2Id": "dat.AbilityId",
        "dat.ResourceMagicObstaclesList.resourceId": "dat.ResourceId",
        "dat.ResourceModifier.id": "dat.ResourceModifierId",
        "dat.ResourceModifier.resourceId": "dat.ResourceId",
        "dat.ResourceType.id": "dat.ResourceTypeId",
        "dat.ResourcesList.costs": "number[]",
        "dat.ResourcesList.id": "dat.ResourceId",
        "dat.ResourcesList.modifierIsPerCosts": "boolean[]",
        "dat.ResourcesList.modifiers": "number[]",
        "dat.ResourcesList.resourceTypeId": "dat.ResourceTypeId",
        "dat.ResourcesList.stockId": "dat.StockId",
        "dat.Ruleset.id": "dat.RulesetId",
        "dat.RulesetExpansion.expansionId": "dat.RulesetId",
        "dat.RulesetExpansion.rulesetId": "dat.RulesetId",
        "dat.RulesetLifepath.lifepathId": "dat.LifepathId",
        "dat.RulesetLifepath.rulesetId": "dat.RulesetId",
        "dat.RulesetResource.resourceId": "dat.ResourceId",
        "dat.RulesetResource.rulesetId": "dat.RulesetId",
        "dat.RulesetSetting.rulesetId": "dat.RulesetId",
        "dat.RulesetSetting.settingId": "dat.SettingId",
        "dat.RulesetSkill.rulesetId": "dat.RulesetId",
        "dat.RulesetSkill.skillId": "dat.SkillId",
        "dat.RulesetStock.rulesetId": "dat.RulesetId",
        "dat.RulesetStock.stockId": "dat.StockId",
        "dat.RulesetTrait.rulesetId": "dat.RulesetId",
        "dat.RulesetTrait.traitId": "dat.TraitId",
        "dat.RulesetsList.expansionIds": "dat.RulesetId[]",
        "dat.RulesetsList.id": "dat.RulesetId",
        "dat.Setting.id": "dat.SettingId",
        "dat.Setting.stockId": "dat.StockId",
        "dat.SettingsList.id": "dat.SettingId",
        "dat.SettingsList.stockId": "dat.StockId",
        "dat.Skill.categoryId": "dat.SkillCategoryId",
        "dat.Skill.id": "dat.SkillId",
        "dat.Skill.restrictionAbilityId": "dat.AbilityId",
        "dat.Skill.restrictionOnlyStockId": "dat.StockId",
        "dat.Skill.root1Id": "dat.AbilityId",
        "dat.Skill.root2Id": "dat.AbilityId",
        "dat.Skill.stockId": "dat.StockId",
        "dat.Skill.toolTypeId": "dat.SkillToolTypeId",
        "dat.Skill.typeId": "dat.SkillTypeId",
        "dat.SkillCategory.id": "dat.SkillCategoryId",
        "dat.SkillSubskill.skillId": "dat.SkillId",
        "dat.SkillSubskill.subskillId": "dat.SkillId",
        "dat.SkillToolType.id": "dat.SkillToolTypeId",
        "dat.SkillType.id": "dat.SkillTypeId",
        "dat.SkillsList.categoryId": "dat.SkillCategoryId",
        "dat.SkillsList.id": "dat.SkillId",
        "dat.SkillsList.restrictionAbilityId": "dat.AbilityId",
        "dat.SkillsList.restrictionOnlyStockId": "dat.StockId",
        "dat.SkillsList.rootIds": "dat.AbilityId[]",
        "dat.SkillsList.stockId": "dat.StockId",
        "dat.SkillsList.subskillIds": "dat.SkillId[]",
        "dat.SkillsList.toolTypeId": "dat.SkillToolTypeId",
        "dat.SkillsList.typeId": "dat.SkillTypeId",
        "dat.SpellAreaOfEffectFacet.id": "dat.SpellAreaOfEffectFacetId",
        "dat.SpellDurationFacet.id": "dat.SpellDurationFacetId",
        "dat.SpellElementFacet.id": "dat.SpellElementFacetId",
        "dat.SpellFacetType.id": "dat.SpellFacetTypeId",
        "dat.SpellImpetusFacet.id": "dat.SpellImpetusFacetId",
        "dat.SpellOriginFacet.id": "dat.SpellOriginFacetId",
        "dat.Stock.id": "dat.StockId",
        "dat.StocksList.id": "dat.StockId",
        "dat.StocksList.settingIds": "dat.SettingId[]",
        "dat.TimeUnit.id": "dat.TimeUnitId",
        "dat.Trait.categoryId": "dat.TraitCategoryId",
        "dat.Trait.id": "dat.TraitId",
        "dat.Trait.stockId": "dat.StockId",
        "dat.Trait.typeId": "dat.TraitTypeId",
        "dat.TraitCategory.id": "dat.TraitCategoryId",
        "dat.TraitType.id": "dat.TraitTypeId",
        "dat.TraitsList.categoryId": "dat.TraitCategoryId",
        "dat.TraitsList.id": "dat.TraitId",
        "dat.TraitsList.stockId": "dat.StockId",
        "dat.TraitsList.typeId": "dat.TraitTypeId",
        "dat.UnitModifier.id": "dat.UnitModifierId",
        "meta.Migration.id": "meta.MigrationId",
        "usr.User.id": "usr.UserId",
        "usr.UserAccess.id": "usr.UserAccessId",
        "usr.UserAccess.userAccessTypeId": "usr.UserAccessTypeId",
        "usr.UserAccess.userId": "usr.UserId",
        "usr.UserAccessType.id": "usr.UserAccessTypeId",
        "usr.UserSession.sess": "unknown"
      }
    })
    .fetchDatabase()
    .mapTables(table => {
      if (table.name.startsWith("v")) {
        return ({ ...table, interfaceName: table.name.charAt(0).toUpperCase() + table.name.slice(1) });
      }
      return ({ ...table, interfaceName: table.name });
    })
    .toTypescript();

  const final =
    initial
      .replaceAll("'", "")
      .replaceAll("export namespace", "declare namespace")
      .replaceAll("export interface", "interface");

  const outputPath = path.join(path.dirname(new URL(import.meta.url).pathname), "../@types", "db.d.ts");

  if (process.argv.includes("--check")) {
    const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf-8") : "";
    if (existing !== final) {
      console.error("db.d.ts is out of date. Run `npm run db:type` to regenerate.");
      process.exit(1);
    }
    console.log("db.d.ts is up to date.");
  }
  else {
    fs.writeFileSync(outputPath, final, "utf-8");
    console.log(`Database types written to ${outputPath}`);
  }
})();
