DROP SCHEMA IF EXISTS dat CASCADE;

DROP SCHEMA IF EXISTS meta CASCADE;

CREATE SCHEMA IF NOT EXISTS meta;

CREATE SCHEMA IF NOT EXISTS dat;

CREATE TABLE IF NOT EXISTS
  meta."Migration" (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "executedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
  );